import { StreamSpec } from './supervisor';
import { relayPort } from '../../lib/relayPort';

export interface MinimalDb {
  all<T = unknown>(sql: string): Promise<T[]>;
}

export interface LoadStreamSpecsOptions {
  db: MinimalDb;
  tableName: string;
}

interface StreamRow {
  id?: number;
  obs_source_name?: string;
  url?: string;
}

// Table names are interpolated (sqlite identifiers can't be parameterized).
// Restrict to the shape generated by lib/constants.ts getTableName():
// <base>_<year>_<season>[_<suffix>] — letters, digits, underscores only.
const SAFE_TABLE_NAME = /^[a-zA-Z][a-zA-Z0-9_]*$/;

export async function loadStreamSpecs(opts: LoadStreamSpecsOptions): Promise<StreamSpec[]> {
  if (!SAFE_TABLE_NAME.test(opts.tableName)) {
    throw new Error(`invalid table name: ${opts.tableName}`);
  }

  const rows = await opts.db.all<StreamRow>(
    `SELECT id, obs_source_name, url FROM ${opts.tableName}`
  );

  return rows
    .filter(r => Number.isInteger(r.id) && (r.id as number) > 0
              && typeof r.obs_source_name === 'string' && r.obs_source_name.length > 0
              && typeof r.url === 'string' && r.url.length > 0)
    .map(r => ({
      streamId: r.obs_source_name!,
      upstreamUrl: r.url!,
      // Deterministic port shared with the webui ffmpeg_source input.
      port: relayPort(r.id!),
    }));
}
